import pyautogui as ui

DIRECTORY = __file__.replace("/constants.py", "")

SCREEN_WIDTH, SCREEN_HEIGHT = ui.size()
SCREEN_CENTER_X = int(SCREEN_WIDTH / 2)
SCREEN_CENTER_Y = int(SCREEN_HEIGHT / 2)
SCREEN_CENTER = (SCREEN_CENTER_X, SCREEN_CENTER_Y)

GAME_WIDTH = 788
GAME_HEIGHT = 1052
GAME_X = SCREEN_CENTER_X - 392
GAME_Y = SCREEN_CENTER_Y - 490
GAME_CENTER_X = int(GAME_WIDTH / 2)
GAME_CENTER_Y = int(GAME_HEIGHT / 2)